name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.9
      - name: Run test
        run: |
          gradle generateAvro
          gradle cleanTest test