name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Wrapper with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 5.6.4
          arguments: wrapper
      - name: Avro with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 5.6.4
          arguments: generateAvro
      - name: Test with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 5.6.4
          arguments: cleanTest test