name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "11"

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.1.1
      - name: Run test
        run: |
          gradle generateAvro
          gradle cleanTest test